In [46]:
import numpy as np
import pandas as pd

In [47]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [48]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [49]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [50]:
date.info()
# in this we can clearly see that the date column is of object type but to perform the operation it should be of datatime data type not object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [51]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with dates

In [52]:
date['date'] = pd.to_datetime(date['date'])

In [53]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1. Extract year

In [54]:
date['date_year'] = date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## 2. Extract month

In [55]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [56]:
# if we want month name then 
date['date_month_no'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year date_month_no
0 2019-12-10        5628       25       3       2019      December
1 2018-08-15        3646       14     157       2018        August
2 2018-10-23        1859       25       1       2018       October
3 2019-08-17        7292       25       1       2019        August
4 2019-01-06        4344       25       3       2019       January

## 3. Extract day no.

In [57]:
date['date_day_no'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day_no
0,2019-12-10,5628,25,3,2019,December,10
1,2018-08-15,3646,14,157,2018,August,15
2,2018-10-23,1859,25,1,2018,October,23
3,2019-08-17,7292,25,1,2019,August,17
4,2019-01-06,4344,25,3,2019,January,6

## # day of week ?

In [58]:

date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day_no,date_dow
0,2019-12-10,5628,25,3,2019,December,10,1
1,2018-08-15,3646,14,157,2018,August,15,2
2,2018-10-23,1859,25,1,2018,October,23,1
3,2019-08-17,7292,25,1,2019,August,17,5
4,2019-01-06,4344,25,3,2019,January,6,6

## # day of week - name

In [59]:

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year date_month_no  date_day_no  date_dow date_dow_name
0 2019-12-10       2019      December           10         1       Tuesday
1 2018-08-15       2018        August           15         2     Wednesday
2 2018-10-23       2018       October           23         1       Tuesday
3 2019-08-17       2019        August           17         5      Saturday
4 2019-01-06       2019       January            6         6        Sunday

## # is weekend ?

In [60]:

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Saturday','Sunday']),1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day_no,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,1,Tuesday,0
1,2018-08-15,2018,August,15,2,Wednesday,0
2,2018-10-23,2018,October,23,1,Tuesday,0
3,2019-08-17,2019,August,17,5,Saturday,1
4,2019-01-06,2019,January,6,6,Sunday,1

## Extract week of the year

In [61]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day_no,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,December,10,1,Tuesday,0,50
1,2018-08-15,2018,August,15,2,Wednesday,0,33
2,2018-10-23,2018,October,23,1,Tuesday,0,43
3,2019-08-17,2019,August,17,5,Saturday,1,33
4,2019-01-06,2019,January,6,6,Sunday,1,1

## Extract Quarter

In [63]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day_no,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,January,6,6,Sunday,1,1,1

## Extract semester

In [64]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day_no,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,January,6,6,Sunday,1,1,1,1

## Extract time elapsed between dats

In [75]:
import datetime 

today = datetime.datetime.today()
today

datetime.datetime(2026, 7, 19, 17, 26, 40, 224262)

In [76]:
today-date['date']

0     2413 days 17:26:40.224262
1     2895 days 17:26:40.224262
2     2826 days 17:26:40.224262
3     2528 days 17:26:40.224262
4     2751 days 17:26:40.224262
                 ...
995   2841 days 17:26:40.224262
996   2782 days 17:26:40.224262
997   2630 days 17:26:40.224262
998   2695 days 17:26:40.224262
999   2469 days 17:26:40.224262
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# days passed 
(today-date['date']).dt.days

0      2413
1      2895
2      2826
3      2528
4      2751
       ...
995    2841
996    2782
997    2630
998    2695
999    2469
Name: date, Length: 1000, dtype: int64

In [ ]:
# Month passed 
np.round((today - date['date']) / np.timedelta64(30, 'D'), 0)

0      80.0
1      97.0
2      94.0
3      84.0
4      92.0
       ...
995    95.0
996    93.0
997    88.0
998    90.0
999    82.0
Name: date, Length: 1000, dtype: float64

# Working with time

In [ ]:
time.info() # date->object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [83]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [84]:
time['date'] = pd.to_datetime(time['date'])

In [85]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [86]:
time['hour'] = time['date'].dt.hour
time['minutes'] = time['date'].dt.minute
time['seconds'] = time['date'].dt.second

In [87]:
time.head()

,date,msg,hour,minutes,seconds
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Extract time part

In [89]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,minutes,seconds,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## time difference

In [90]:
today - time['date']

0     4599 days 16:36:40.224262
1     4463 days 17:46:40.224262
2     4949 days 17:05:40.224262
3     4251 days 16:55:40.224262
4     4648 days 18:15:40.224262
                 ...
995   5238 days 16:36:40.224262
996   4559 days 18:12:40.224262
997   5024 days 17:49:40.224262
998   5140 days 17:52:40.224262
999   4412 days 18:01:40.224262
Name: date, Length: 1000, dtype: timedelta64[ns]

In [91]:
# in seconds 
(today-time['date'])/np.timedelta64(1,'s')

0      3.974134e+08
1      3.856672e+08
2      4.276551e+08
3      3.673473e+08
4      4.016529e+08
           ...
995    4.526230e+08
996    3.939632e+08
997    4.341378e+08
998    4.441604e+08
999    3.812617e+08
Name: date, Length: 1000, dtype: float64

In [92]:

# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.623557e+06
1      6.427787e+06
2      7.127586e+06
3      6.122456e+06
4      6.694216e+06
           ...
995    7.543717e+06
996    6.566053e+06
997    7.235630e+06
998    7.402673e+06
999    6.354362e+06
Name: date, Length: 1000, dtype: float64

In [93]:

# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      110392.611173
1      107129.777840
2      118793.094507
3      102040.927840
4      111570.261173
           ...
995    125728.611173
996    109434.211173
997    120593.827840
998    123377.877840
999    105906.027840
Name: date, Length: 1000, dtype: float64