In [40]:
import numpy as np
import pandas as pd

In [41]:
df = pd.read_csv("cars.csv")

In [42]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [43]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [44]:
df['brand'].nunique() # Give the total number of unique elements in that column

32

In [45]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [46]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

# 1) One hot encoding using pandas

In [48]:
pd.get_dummies(df,columns=['owner','fuel']) # now in owner coulmns there was 5 categories and in fuel column there was 4 different categories now using pd.get_dummies we get one hot encoding and through that 5 different columns of owner are created and 4 different columns of fuel are created . But we have not solved the problem of multicollineratiy till now

,brand,km_driven,selling_price,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,True,False,False,False,False,False,True,False,False
1,Skoda,120000,370000,False,False,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,True,False,False
4,Maruti,120000,130000,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,True,False,False,False,False,False,False,False,True
8124,Hyundai,119000,135000,False,True,False,False,False,False,True,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,True,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,True,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,True,False,False

### now removing one column

# 2) k-1 One hot encoding

In [49]:
pd.get_dummies(df,columns=['owner','fuel'],drop_first=True)

,brand,km_driven,selling_price,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,False,False,False,False,True,False,False
1,Skoda,120000,370000,False,True,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,True
3,Hyundai,127000,225000,False,False,False,False,True,False,False
4,Maruti,120000,130000,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,False,False,False,True
8124,Hyundai,119000,135000,True,False,False,False,True,False,False
8125,Maruti,120000,382000,False,False,False,False,True,False,False
8126,Tata,25000,290000,False,False,False,False,True,False,False
8127,Tata,25000,290000,False,False,False,False,True,False,False

### But there is a problem with pandas.get_duumies and we can't use this on large scale or on ml Projects because pd.get_dummies do not remember the position of the columns and everytimme when we run we get different position of columns . So instead of using this we use the library of sciklet learn

# 3) One hot encoding using sklearn

In [50]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [51]:
from sklearn.model_selection import train_test_split  
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=42)

In [52]:
X_train.head() # in X_train there are only input columns

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [53]:
from sklearn.preprocessing import OneHotEncoder

In [63]:
ohe = OneHotEncoder(drop='first') # created object of one hot encoder  # It drops the first columns for removing the multicollineraity problem 
# there is one more parameter called sparse = Flase -> using this we do not need to use .toarray() as by using sparse = True we will get sparse array 
# we can also set the datatype like in final result we below the datatype is float in some columns which can be replaced by int so we can write dtype=np.int32

In [55]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [56]:
X_test_new = ohe.fit_transform(X_train[['owner','fuel']]).toarray()

In [57]:
X_train_new # This is an numpy array. # Now will merge with other columns  ()

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(6502, 7))

In [58]:
X_train[['brand','km_driven']].values # this is also numpy array

array([['Tata', 2560],
       ['Honda', 80000],
       ['Hyundai', 150000],
       ...,
       ['Hyundai', 35000],
       ['Maruti', 27000],
       ['Maruti', 70000]], shape=(6502, 2), dtype=object)

now we get all pair of 2 input columns in numpy array and we will horizontally stack it for final encoded table

In [59]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Tata', 2560, 0.0, ..., 0.0, 0.0, 0.0],
       ['Honda', 80000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Hyundai', 150000, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 27000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 70000, 0.0, ..., 1.0, 0.0, 0.0]],
      shape=(6502, 9), dtype=object)

In [60]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

# 4) One Hot encoding with top categories

In [64]:
counts = df['brand'].value_counts()

In [65]:
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [66]:
df['brand'].nunique()
threshold = 100

In [67]:
repl = counts[counts<=threshold].index

In [68]:
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [71]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2723,False,True,False,False,False,False,False,False,False,False,False,False,False
3675,False,False,False,False,False,False,True,False,False,False,False,False,False
5652,False,False,True,False,False,False,False,False,False,False,False,False,False
3187,False,False,False,False,True,False,False,False,False,False,False,False,False
3545,False,False,True,False,False,False,False,False,False,False,False,False,False